version: '3.9'
services:
  postgres:
    image: postgres:15.3-alpine
    environment:
      POSTGRES_DB: quarkus-playground
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U root -d quarkus-playground"]
      interval: 10s
      timeout: 3s
      retries: 5
