quarkus:
  application:
    name: quarkus-playground

  datasource:
    devservices:
      image-name: postgres:15.3-alpine

  flyway:
    migrate-at-start: true

  log:
    category:
      "com.github.bkhablenko":
        level: DEBUG
