quarkus:
  application:
    name: quarkus-playground

  datasource:
    db-kind: postgresql
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password}
    jdbc:
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:${quarkus.application.name}}

  flyway:
    migrate-at-start: true

  log:
    category:
      com.github.bkhablenko:
        level: DEBUG
